AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda resources for iac-learn.

Parameters:
  ProjectName:
    Type: String
  FunctionName:
    Type: String
  Runtime:
    Type: String
    Default: python3.12
  Handler:
    Type: String
    Default: handler.handler
  CodeS3Bucket:
    Type: String
  CodeS3Key:
    Type: String
  CodeS3ObjectVersion:
    Type: String
    Default: ""

Conditions:
  HasCodeVersion: !Not [!Equals [!Ref CodeS3ObjectVersion, ""]]

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${FunctionName}-exec"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${FunctionName}"
      RetentionInDays: 7

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: !Ref Runtime
      Handler: !Ref Handler
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
        S3ObjectVersion: !If
          - HasCodeVersion
          - !Ref CodeS3ObjectVersion
          - !Ref AWS::NoValue

Outputs:
  FunctionArn:
    Value: !GetAtt LambdaFunction.Arn
  FunctionName:
    Value: !Ref LambdaFunction
